#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage:  init <filename>"
    exit 62
elif [ -f "$1.atm" ] || [ -f "$1.bank" ]; then
    echo "Error: one of the files already exists"
    exit 63
fi

openssl genrsa -out "$1.bank" 4096 2>/dev/null &&
# openssl rsa -in "$1.bank" -pubout -out "$1.atm" 2>/dev/null ||
cp "$1.bank" "$1.atm" ||
(
    echo "Error creating initialization files"
    exit 64
) && (
    echo "Successfully initialized bank state"
    exit 0
)
